version: '3.8'

services:
  app:
    build: .
    container_name: order-btg-php
    volumes:
      - .:/var/www/html
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - order-btg-network
  nginx:
    build: .docker/nginx
    container_name: order-btg-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - order-btg-network  
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: order-btg-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  
    networks:
      - order-btg-network  
    volumes:
      - .docker/dbdata:/var/lib/mysql

networks:
  order-btg-network:
    driver: bridge
